version: '3'
services:
  db_users:
    image: postgres:16
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: weather_hub_db
